### ISSUE TITLE
私有pod引用此pod的问题

### ISSUE THREAD

**Issue by ccloong** [shingwasix/TIMSDK#5]
Hi，

不知道你们有没有试过将此pod作为private pod的dependency引入的操作，此时在private pod的类里面无法引用到TIMSDK pod的头文件。不知道是不是TIMSDK.podspec配置的问题？

**Comment by shingwasix** [comment]
你确定执行`pod install`安装的时候有安装TIMSDK成功吗？

**Comment by ccloong** [comment]
安装pod是成功的，命令行提示install成功，并且pods目录下都存在TIMSDK的目录。

**Comment by ccloong** [comment]
![2017-03-15 17 32 55](https://cloud.githubusercontent.com/assets/8212827/23941949/a96e0a82-09a5-11e7-8a74-2bce49d4d7bf.png)
能帮忙看下这个问题吗

**Comment by shingwasix** [comment]
```<ImSDK/ImSDK.h>```，不是```<IMSDK/IMSDK.h>```

**Comment by ccloong** [comment]
oops~我试下，因为不能自动提示。

**Comment by ccloong** [comment]
不过还是不行，找不到<ImSDK/ImSDK.h>
头文件

**Comment by ccloong** [comment]
另外在pod上面Example的工程里面是可以顺利引用ImSDK的。

**Comment by shingwasix** [comment]
看看你的podspec文件是怎么设置依赖TIMSDK的

**Comment by ccloong** [comment]
我创建了git

**Comment by ccloong** [comment]
我创建了个demo
https://github.com/ccloong/MayuePod2
pod工程里面有个TestClass，在这里面是找不到ImSDK的；但是在demo example工程的appdelegate里面，是可以引用到ImSDK的。请帮忙看下。

多谢！~~~

**Comment by shingwasix** [comment]
Podfile文件去掉```use_frameworks!```

**Comment by ccloong** [comment]
去掉use_frameworks问题解决！！！
多谢！！！
